name: CI

on:
  push:
    branches: [master]  # 또는 병덕이 작업 중인 브랜치 이름으로 수정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 병덕 프로젝트에 맞는 Node 버전으로 조정 가능

      - name: Install dependencies
        run: yarn install

      - name: Build (Ignore ESLint warnings)
        run: CI='' yarn build
